---
# tasks file for ansible-private-common
- name: get rid of RHUI repo files if present
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/yum.repos.d/redhat.repo"
    - "/etc/yum.repos.d/redhat-rhui.repo"
    - "/etc/yum.repos.d/redhat-rhui-client-config.repo"
    - "/etc/yum.repos.d/rhui-load-balancers.conf"

- name: set up disconnected yum repo
  copy:
    src: "./{{ cluster_id }}.repo"
    dest: "/etc/yum.repos.d/{{ cluster_id }}.repo"
    owner: root
    mode: 0644

- name: make yum cache
  command: yum makecache
  async: 1200
  poll: 60